---
labels:
  nirmata.io/clusterspec.version: v1.9.1
version: v1.9.1
authorization:
  mode: rbac
components:
- name: etcd
  image: gcr.io/google_containers/etcd:3.0.14
  args: {}
- name: apiserver
  image: gcr.io/google_containers/hyperkube:v1.9.1
  args:
    allow-privileged: "true"
    client-ca-file: /etc/kubernetes/ssl/ca.crt
    tls-cert-file: /etc/kubernetes/ssl/server.crt
    tls-private-key-file: /etc/kubernetes/ssl/server.key
    service-account-key-file: /etc/kubernetes/ssl/server.key
    etcd-cafile: /etc/kubernetes/ssl/ca.crt
    etcd-certfile: /etc/kubernetes/ssl/etcd-client.crt
    etcd-keyfile: /etc/kubernetes/ssl/etcd-client.key
    admission-control: Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota
    authorization-mode: RBAC,Node
    requestheader-client-ca-file: /etc/kubernetes/ssl/aggregator-ca.crt
    requestheader-allowed-names: aggregator
    requestheader-extra-headers-prefix: X-Remote-Extra-
    requestheader-group-headers: X-Remote-Group
    requestheader-username-headers: X-Remote-User
    enable-aggregator-routing: "true"
    service-cluster-ip-range: 10.10.0.0/16
- name: controller-manager
  image: gcr.io/google_containers/hyperkube:v1.9.1
  args:
    service-account-private-key-file: /etc/kubernetes/ssl/server.key
    root-ca-file: /etc/kubernetes/ssl/ca.crt
    master: http://{NIRMATA_HOST_PRIVATE_ADDRESS}:8080
    allocate-node-cidrs: "true"
    cluster-cidr: 10.244.0.0/16
- name: scheduler
  image: gcr.io/google_containers/hyperkube:v1.9.1
  args:
    master: http://{NIRMATA_HOST_PRIVATE_ADDRESS}:8080
- name: kubelet
  image: gcr.io/google_containers/hyperkube:v1.9.1
  args:
    kubeconfig: /var/lib/kubeconfig/kubelet.yaml
    allow-privileged: "true"
    container-runtime: docker
    pod-manifest-path: /etc/kubernetes/manifests
    network-plugin: cni
    cni-conf-dir: /etc/cni/net.d
    cni-bin-dir: /opt/cni/bin
    cluster-domain: cluster.local
    fail-swap-on: "false"
    hostname-override: '{NIRMATA_HOST_PRIVATE_DNS_NAME}'
    cluster-dns: 10.10.0.10
- name: proxy
  image: gcr.io/google_containers/hyperkube:v1.9.1
  args:
    kubeconfig: /var/lib/kubeconfig/proxy.yaml
addons:
  dns: true
